# Generated by Django 4.2.3 on 2023-08-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contato_lido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['-data'], 'verbose_name': 'Formulário de Contato', 'verbose_name_plural': 'Formulários de Contato'},
        ),
    ]
