# Generated by Django 4.2.3 on 2023-08-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('nome_pet', models.CharField(max_length=50)),
                ('porte', models.CharField(choices=[(0, 'Pequeno'), (1, 'Médio'), (2, 'Grande')], max_length=120)),
                ('data_reserva', models.DateField(help_text='Ultilize o formato dd/mm/aaaa')),
                ('turno', models.CharField(choices=[('manhã', 'Manhã'), ('tarde', 'Tarde')], max_length=120)),
                ('observacoes', models.TextField(blank=True, max_length=3000, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Reserva de Banho',
                'verbose_name_plural': 'Reservas de banho',
            },
        ),
    ]
