# Generated by Django 4.2.3 on 2023-10-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_reserva_petshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(blank=True, help_text='Ultilize o formato dd/mm/aaaa', null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='porte',
            field=models.IntegerField(blank=True, choices=[(0, 'Pequeno'), (1, 'Médio'), (2, 'Grande')], null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='turno',
            field=models.CharField(blank=True, choices=[('manhã', 'Manhã'), ('tarde', 'Tarde')], max_length=120),
        ),
    ]
