# Generated by Django 4.2.1 on 2023-10-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_categoriaanimal_remove_reserva_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reserva.categoriaanimal'),
        ),
    ]
