# Generated by Django 4.2.4 on 2023-10-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_alter_reserva_data_reserva_alter_reserva_porte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(help_text='Ultilize o formato dd/mm/aaaa'),
        ),
    ]
