# Generated by Django 4.2.3 on 2023-10-27 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_alter_categoriaanimal_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, 'A nota deve ser no mínimo 0.'), django.core.validators.MaxValueValidator(10, 'A nota deve ser no máximo 10.')]),
        ),
    ]
