# Generated by Django 4.2.3 on 2023-10-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_alter_avaliacao_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petshop',
            options={},
        ),
    ]
