# Generated by Django 4.2.4 on 2023-10-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_alter_reserva_data_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(blank=True, help_text='Ultilize o formato dd/mm/aaaa', null=True),
        ),
    ]
