# Generated by Django 4.2.3 on 2023-10-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_alter_petshop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petshop',
            options={'ordering': ['nome'], 'verbose_name': 'Petshop', 'verbose_name_plural': 'Petshops'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['nome', 'email', 'nome_pet', 'porte', 'data_reserva', 'turno', 'observacoes', 'petshop', 'categoria'], 'verbose_name': 'Reserva de Banho', 'verbose_name_plural': 'Reservas de banho'},
        ),
    ]
